### ISSUE TITLE
Frame-rate usb_cam

### ISSUE THREAD

**Issue by jbler** [Rentier/ros-panopticon#1]
Hi,

I would like to know if there is a reason for setting the frame rate of the usb cams as low as 10Hz instead of using the maximum frame-rate of 30Hz?

**Comment by jcklie** [comment]
There were two reason why I set it so low:
-  for recording purposes (the bag uncompressed gets really huge already, so even more with higher frame rate)
- the camera nodes sometimes stopped working with a timeout error, and I thought it might be that the single USB card cannot handle the load. Now that does not happen anymore, I do not know why but I am happy that everything works.

If these two reasons to not apply, then there is no reason why you cannot set the frame rate higher.

**Comment by jbler** [comment]
Thanks for your fast reply. I will give it a try tomorrow.
